version: "2"

services:
  aspnet-efcore-test:
    image: aspnet-efcore-test
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTP_PORT: 80
      ASPNETCORE_HTTPS_PORT: 443
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_SSL_PW}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/certs/localhost.pfx
    volumes:
      - './certs/localhost.pfx:/app/certs/localhost.pfx'
    ports:
      - 5000:80
      - 5001:443
